# Site settings
title: Void No Logo
email: caleb@voidnologo.com
description: Sed fugit interea, fugit irreparabile tempus.
#  "But meanwhile it is flying, irretrievable time is flying."
# > # this means to ignore newlines until "baseurl:"
#   Write an awesome description for your new site here. You can edit this
#   line in _config.yml. It will appear in your document head meta (for
#   Google search results) and in your feed.xml site description.
#

production_url: http://voidnologo.github.io

# baseurl: "" # the subpath of your site, e.g. /blog/
# url: "http://yourdomain.com" # the base hostname & protocol for your site
github_username: voidnologo
permalink: /:year/:month/:day/:title/
# this is the url root of the view source link on the footer page.
viewsourceroot: https://github.com/voidnologo/voidnologo.github.io/blob/master/
# this is the url root of the create page link on the footer page.
newsourceroot: https://github.com/voidnologo/voidnologo.github.io/new/master
#########################################

# Build settings
markdown: kramdown

kramdown:
    input: GFM
    syntax_highlighter: rouge

# highlight
# highlighter: pygments
highlighter: rouge
# highlighter: false
#
author :
  name : Caleb Salt
  email : void.no.logo@gmail.com
  github : voidnologo
